# **Learning about Column Transformer**

In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df['cough'].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [6]:
df['city'].value_counts()

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:5], df.iloc[:,-1], test_size=0.2)

In [16]:
x_train

age  gender  fever   cough       city
52   47  Female  100.0  Strong  Bangalore
1    27    Male  100.0    Mild      Delhi
6    14    Male  101.0  Strong  Bangalore
91   38    Male    NaN    Mild      Delhi
55   81  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
37   55    Male  100.0    Mild    Kolkata
16   69  Female  103.0    Mild    Kolkata
46   19  Female  101.0    Mild     Mumbai
94   79    Male    NaN  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore

[80 rows x 5 columns]

# Without using column transformer

**Aam Zindagi**

**We will use simpleImputer class to fill our empty data values in fever column by its mean**

In [20]:
# adding simple imputer to fever column
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])
x_test_fever = si.fit_transform(x_test[['fever']])

In [21]:
x_train_fever

array([[100.],
       [100.],
       [101.],
       [101.],
       [101.],
       [101.],
       [104.],
       [101.],
       [101.],
       [101.],
       [ 99.],
       [ 98.],
       [100.],
       [101.],
       [ 98.],
       [100.],
       [ 99.],
       [100.],
       [104.],
       [101.],
       [100.],
       [ 98.],
       [101.],
       [100.],
       [104.],
       [104.],
       [ 98.],
       [102.],
       [104.],
       [ 98.],
       [101.],
       [103.],
       [100.],
       [ 98.],
       [101.],
       [101.],
       [104.],
       [ 98.],
       [101.],
       [ 98.],
       [101.],
       [103.],
       [103.],
       [102.],
       [102.],
       [ 98.],
       [102.],
       [104.],
       [ 98.],
       [ 99.],
       [101.],
       [101.],
       [102.],
       [104.],
       [102.],
       [ 99.],
       [104.],
       [ 99.],
       [ 98.],
       [101.],
       [101.],
       [104.],
       [102.],
       [101.],
       [103.],
       [102.],
       [10

In [22]:
x_train.shape

(80, 5)

**Ordinal Encoding on 'cough' column**

In [54]:
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])

In [31]:
x_train_cough

array([[1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [32]:
x_train_cough.shape

(80, 1)

**OneHotEncoding for 'gender' and 'city' columns**

In [37]:
ohe = OneHotEncoder(drop = 'first', sparse_output=False, dtype = np.int32)
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])
x_test_gender_city = ohe.fit_transform(x_test[['gender', 'city']])

In [38]:
x_train_gender_city

array([[0, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 1,

In [48]:
x_train_gender_city.shape

(80, 4)

**Extracting age**

In [45]:
x_train_age = x_train.drop(columns = ['gender','fever','cough','city']).values
x_test_age = x_test.drop(columns = ['gender','fever','cough','city']).values

In [47]:
x_train_age.shape

(80, 1)

# Join all the arrays together

In [55]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis = 1)
x_test_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis = 1)

In [56]:
x_train_transformed.shape

(80, 7)

# Doing same thing using Column Transformer class

**Mentos Zindagi**

In [57]:
from sklearn.compose import ColumnTransformer

**Inside the transformer we will pass the different columns to tranform using the tranformation that we need**

**first will pass the name of the tranformation that we want**

**than the type of transformation we need and it's column next**

In [63]:
transformer = ColumnTransformer(transformers=[
    ('tns1', SimpleImputer(), ['fever']),
    ('tns2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tns3', OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32), ['gender', 'city'])
    ],remainder='passthrough'
) 

In [64]:
transformer.fit_transform(x_train)

array([[100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [101.,   1.,   0.,   1.,